[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit_token_to_user_ata = "29dme7kugTJtCNVkUboAiTfSZVMWFqp7v6LYUWuuN66R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/codeedoc/.config/solana/c"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
